package:
  format-version: "1.0.0"
  name: "mplab_event_recorder"
  type: "api"
  status: "production"
  required: false
  version: "v1.1.0"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "v3.12.0"
    - name: "csp"
      type: "package"
      version: "v3.16.0"
    - name: "CMSIS-View"
      type: "package"
      version: "v1.1.0"
